name: Release

on:
  push:
    tags:
      - "**"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run check
        run: cargo check --locked

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run test
        run: cargo test

  package:
    needs: check
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set package info
        run: |
          $metadata = cargo metadata --no-deps --format-version 1 --locked | ConvertFrom-Json
          $name = $metadata.packages[0].name
          "NAME=$name" >> $env:GITHUB_ENV

      - name: Build release
        run: cargo build --locked --release --verbose

      - name: Package release
        uses: vimtor/action-zip@v1
        with:
          files: target/release/${{ env.NAME }}.exe
          dest: ${{ env.NAME }}-${{ github.ref_name }}-win-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.NAME }}-${{ github.ref_name }}-win-x64.zip
          path: ${{ env.NAME }}-${{ github.ref_name }}-win-x64.zip
          if-no-files-found: error

  release:
    needs: package
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*.zip
          generate_release_notes: true
          fail_on_unmatched_files: true
